function [yOut,arrayTx] = processor_goldenModel(arrayInput,cfgStruct)

%% range estimation
correctionPhase = ...
    mod(...
    2*pi...
    *cfgStruct.scenario.objCfgVec{1}.sourceMinFreq ...
    *cfgStruct.IdealEstimation.objSeperatedRxDelays_CELL{1}{1}...
    (...
    cfgStruct.dynamics.startSampleID ...
    ) ...
    ,2*pi);

%% feedback synthesis
arrayTx = ...
    [...
    arrayInput(:,2:end)*exp(-1i*correctionPhase)*cfgStruct.filter.sensorWeights(:) ...
    zeros(size(arrayInput,1),size(arrayInput,2)-1) ...
    ];

%% array output calc
yOut = ...
    arrayInput(:,1);

end