function [] = vsbEval()
syms x y r q w1 w2 t tau real;

tx = (x*cos(w1*t)-y*sin(w1*t))*cos(w2*t)-(r*cos(w1*t)-q*sin(w1*t))*sin(w2*t);

RX = subs(tx,t,t-tau);

RX1_init = [RX*cos(w2*t),-RX*sin(w2*t)];
RX1 = combine(simplifyFraction(RX1_init,'Expand',true),'sincos');

RX1_preLPF = ...
    (q*cos(t*w1 - tau*w1 + tau*w2))/4 ...
    - ...
    (q*cos(tau*w1 - t*w1 + tau*w2))/4 ...
    + ...
    (x*cos(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (x*cos(tau*w1 - t*w1 + tau*w2))/4 ...
    + ...
    (r*sin(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (r*sin(tau*w1 - t*w1 + tau*w2))/4 ...
    - ...
    (y*sin(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (y*sin(tau*w1 - t*w1 + tau*w2))/4 ...
    + ...
    (q*cos(t*w1 - 2*t*w2 - tau*w1 + tau*w2))/4 ...
    - ...
    (q*cos(t*w1 + 2*t*w2 - tau*w1 - tau*w2))/4 ...
    + ...
    (x*cos(t*w1 - 2*t*w2 - tau*w1 + tau*w2))/4 ...
    + ...
    (x*cos(t*w1 + 2*t*w2 - tau*w1 - tau*w2))/4 ...
    + ...
    (r*sin(t*w1 - 2*t*w2 - tau*w1 + tau*w2))/4 ...
    - ...
    (r*sin(t*w1 + 2*t*w2 - tau*w1 - tau*w2))/4 ...
    - ...
    (y*sin(t*w1 - 2*t*w2 - tau*w1 + tau*w2))/4 ...
    - ...
    (y*sin(t*w1 + 2*t*w2 - tau*w1 - tau*w2))/4;


RX1_postLPF = ...
    (q*cos(t*w1 - tau*w1 + tau*w2))/4 ...
    - ...
    (q*cos(tau*w1 - t*w1 + tau*w2))/4 ...
    + ...
    (x*cos(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (x*cos(tau*w1 - t*w1 + tau*w2))/4 ...
    + ...
    (r*sin(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (r*sin(tau*w1 - t*w1 + tau*w2))/4 ...
    - ...
    (y*sin(t*w1 - tau*w1 + tau*w2))/4 ...
    + ...
    (y*sin(tau*w1 - t*w1 + tau*w2))/4;

RX2_11_preLPF_auto = ...
    combine(simplifyFraction(RX1_postLPF*cos(w1*t),'Expand',true),'sincos');

RX2_12_preLPF_auto = ...
    combine(simplifyFraction(-RX1_postLPF*sin(w1*t),'Expand',true),'sincos');

RX2_11_preLPF = ...
    (q*cos(tau*w1 - tau*w2))/8 ...
    - ...
    (q*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (x*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (x*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (r*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (r*sin(tau*w1 - tau*w2))/8 ...
    + ...
    (y*sin(tau*w1 + tau*w2))/8 ...
    + ...
    (y*sin(tau*w1 - tau*w2))/8 ...
    - ...
    (q*cos(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    + ...
    (q*cos(2*t*w1 - tau*w1 + tau*w2))/8 ...
    + ...
    (x*cos(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    + ...
    (x*cos(2*t*w1 - tau*w1 + tau*w2))/8 ...
    + ...
    (r*sin(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    + ...
    (r*sin(2*t*w1 - tau*w1 + tau*w2))/8 ...
    + ...
    (y*sin(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    - ...
    (y*sin(2*t*w1 - tau*w1 + tau*w2))/8;


RX2_12_preLPF_ = ...
    (r*cos(tau*w1 + tau*w2))/8 ...
    - ...
    (r*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (y*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (y*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (q*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (q*sin(tau*w1 - tau*w2))/8 ...
    - ...
    (x*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (x*sin(tau*w1 - tau*w2))/8 ...
    - ...
    (r*cos(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    + ...
    (r*cos(2*t*w1 - tau*w1 + tau*w2))/8 ...
    - ...
    (y*cos(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    - ...
    (y*cos(2*t*w1 - tau*w1 + tau*w2))/8 ...
    - ...
    (q*sin(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    - ...
    (q*sin(2*t*w1 - tau*w1 + tau*w2))/8 ...
    + ...
    (x*sin(tau*w1 - 2*t*w1 + tau*w2))/8 ...
    - ...
    (x*sin(2*t*w1 - tau*w1 + tau*w2))/8;

RX2_11_postLPF = ...
    (q*cos(tau*w1 - tau*w2))/8 ...
    - ...
    (q*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (x*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (x*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (r*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (r*sin(tau*w1 - tau*w2))/8 ...
    + ...
    (y*sin(tau*w1 + tau*w2))/8 ...
    + ...
    (y*sin(tau*w1 - tau*w2))/8;

RX2_12_preLPF = ...
    (r*cos(tau*w1 + tau*w2))/8 ...
    - ...
    (r*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (y*cos(tau*w1 + tau*w2))/8 ...
    + ...
    (y*cos(tau*w1 - tau*w2))/8 ...
    + ...
    (q*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (q*sin(tau*w1 - tau*w2))/8 ...
    - ...
    (x*sin(tau*w1 + tau*w2))/8 ...
    - ...
    (x*sin(tau*w1 - tau*w2))/8;
    
RX2_11 = combine(simplifyFraction(simplify(RX2_12_preLPF),'Expand',true),'sincos');
end