function [STR] = genComplexDotPolarSTR(a,b)
if nargin==1
    inputIsPolar=0;
else
    inputIsPolar=1;
end
if inputIsPolar
    r   = a;
    phi = b;
    STR = [num2str(r) 'e^j' f_make_superscript(num2str(phi/pi)) '^\pi'];
end
end
function [superscritptSTR] = f_make_superscript(str)
superscritptSTR = ...
    reshape(...
    [...
    repmat('^',1,numel(str)) ...
    ; ...
    reshape(str,1,[]) ...
    ]...
    ,1,[]);
end